name: Lint Go PR

on:
  pull_request:
    branches:
      - master
    paths:
      - "go/**"
jobs:
  lint-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
